//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model.alexa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataUrl" type="{http://awis.amazonaws.com/doc/2005-07-11}DataUrlType"/>
 *         &lt;element name="Asin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SiteData" type="{http://awis.amazonaws.com/doc/2005-07-11}SiteDataType"/>
 *         &lt;element name="Speed" type="{http://awis.amazonaws.com/doc/2005-07-11}SpeedType"/>
 *         &lt;element name="AdultContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Language" type="{http://awis.amazonaws.com/doc/2005-07-11}LanguageType"/>
 *         &lt;element name="LinksInCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OwnedDomains" type="{http://awis.amazonaws.com/doc/2005-07-11}OwnedDomainsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentDataType", propOrder = {
    "dataUrl",
    "asin",
    "siteData",
    "speed",
    "adultContent",
    "language",
    "linksInCount",
    "ownedDomains"
})
public class ContentDataType {

    @XmlElement(name = "DataUrl", required = true)
    protected DataUrlType dataUrl;
    @XmlElement(name = "Asin", required = true)
    protected String asin;
    @XmlElement(name = "SiteData", required = true)
    protected SiteDataType siteData;
    @XmlElement(name = "Speed", required = true)
    protected SpeedType speed;
    @XmlElement(name = "AdultContent", required = true)
    protected String adultContent;
    @XmlElement(name = "Language", required = true)
    protected LanguageType language;
    @XmlElement(name = "LinksInCount")
    protected int linksInCount;
    @XmlElement(name = "OwnedDomains", required = true)
    protected OwnedDomainsType ownedDomains;

    /**
     * Gets the value of the dataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DataUrlType }
     *     
     */
    public DataUrlType getDataUrl() {
        return dataUrl;
    }

    /**
     * Sets the value of the dataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataUrlType }
     *     
     */
    public void setDataUrl(DataUrlType value) {
        this.dataUrl = value;
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsin() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsin(String value) {
        this.asin = value;
    }

    /**
     * Gets the value of the siteData property.
     * 
     * @return
     *     possible object is
     *     {@link SiteDataType }
     *     
     */
    public SiteDataType getSiteData() {
        return siteData;
    }

    /**
     * Sets the value of the siteData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteDataType }
     *     
     */
    public void setSiteData(SiteDataType value) {
        this.siteData = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedType }
     *     
     */
    public SpeedType getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedType }
     *     
     */
    public void setSpeed(SpeedType value) {
        this.speed = value;
    }

    /**
     * Gets the value of the adultContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdultContent() {
        return adultContent;
    }

    /**
     * Sets the value of the adultContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdultContent(String value) {
        this.adultContent = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageType }
     *     
     */
    public LanguageType getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *     
     */
    public void setLanguage(LanguageType value) {
        this.language = value;
    }

    /**
     * Gets the value of the linksInCount property.
     * 
     */
    public int getLinksInCount() {
        return linksInCount;
    }

    /**
     * Sets the value of the linksInCount property.
     * 
     */
    public void setLinksInCount(int value) {
        this.linksInCount = value;
    }

    /**
     * Gets the value of the ownedDomains property.
     * 
     * @return
     *     possible object is
     *     {@link OwnedDomainsType }
     *     
     */
    public OwnedDomainsType getOwnedDomains() {
        return ownedDomains;
    }

    /**
     * Sets the value of the ownedDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnedDomainsType }
     *     
     */
    public void setOwnedDomains(OwnedDomainsType value) {
        this.ownedDomains = value;
    }

}
