//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model.alexa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PageViewsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageViewsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PerMillion" type="{http://awis.amazonaws.com/doc/2005-07-11}PerMillionType"/>
 *         &lt;element name="Rank" type="{http://awis.amazonaws.com/doc/2005-07-11}RankType"/>
 *         &lt;element name="PerUser" type="{http://awis.amazonaws.com/doc/2005-07-11}PerUserType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageViewsType", propOrder = {
    "perMillion",
    "rank",
    "perUser"
})
public class PageViewsType {

    @XmlElement(name = "PerMillion", required = true)
    protected PerMillionType perMillion;
    @XmlElement(name = "Rank", required = true)
    protected RankType rank;
    @XmlElement(name = "PerUser", required = true)
    protected PerUserType perUser;

    /**
     * Gets the value of the perMillion property.
     * 
     * @return
     *     possible object is
     *     {@link PerMillionType }
     *     
     */
    public PerMillionType getPerMillion() {
        return perMillion;
    }

    /**
     * Sets the value of the perMillion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerMillionType }
     *     
     */
    public void setPerMillion(PerMillionType value) {
        this.perMillion = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link RankType }
     *     
     */
    public RankType getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link RankType }
     *     
     */
    public void setRank(RankType value) {
        this.rank = value;
    }

    /**
     * Gets the value of the perUser property.
     * 
     * @return
     *     possible object is
     *     {@link PerUserType }
     *     
     */
    public PerUserType getPerUser() {
        return perUser;
    }

    /**
     * Sets the value of the perUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerUserType }
     *     
     */
    public void setPerUser(PerUserType value) {
        this.perUser = value;
    }

}
