//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model.alexa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataUrl" type="{http://awis.amazonaws.com/doc/2005-07-11}DataUrlType"/>
 *         &lt;element name="Asin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RelatedLinks" type="{http://awis.amazonaws.com/doc/2005-07-11}RelatedLinksType"/>
 *         &lt;element name="Categories" type="{http://awis.amazonaws.com/doc/2005-07-11}CategoriesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedType", propOrder = {
    "dataUrl",
    "asin",
    "relatedLinks",
    "categories"
})
public class RelatedType {

    @XmlElement(name = "DataUrl", required = true)
    protected DataUrlType dataUrl;
    @XmlElement(name = "Asin", required = true)
    protected String asin;
    @XmlElement(name = "RelatedLinks", required = true)
    protected RelatedLinksType relatedLinks;
    @XmlElement(name = "Categories", required = true)
    protected CategoriesType categories;

    /**
     * Gets the value of the dataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DataUrlType }
     *     
     */
    public DataUrlType getDataUrl() {
        return dataUrl;
    }

    /**
     * Sets the value of the dataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataUrlType }
     *     
     */
    public void setDataUrl(DataUrlType value) {
        this.dataUrl = value;
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsin() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsin(String value) {
        this.asin = value;
    }

    /**
     * Gets the value of the relatedLinks property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedLinksType }
     *     
     */
    public RelatedLinksType getRelatedLinks() {
        return relatedLinks;
    }

    /**
     * Sets the value of the relatedLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedLinksType }
     *     
     */
    public void setRelatedLinks(RelatedLinksType value) {
        this.relatedLinks = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriesType }
     *     
     */
    public CategoriesType getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriesType }
     *     
     */
    public void setCategories(CategoriesType value) {
        this.categories = value;
    }

}
