//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model.alexa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedLinkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedLinkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataUrl" type="{http://awis.amazonaws.com/doc/2005-07-11}DataUrlType"/>
 *         &lt;element name="NavigableUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Asin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Relevance" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedLinkType", propOrder = {
    "dataUrl",
    "navigableUrl",
    "asin",
    "relevance"
})
public class RelatedLinkType {

    @XmlElement(name = "DataUrl", required = true)
    protected DataUrlType dataUrl;
    @XmlElement(name = "NavigableUrl", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String navigableUrl;
    @XmlElement(name = "Asin", required = true)
    protected String asin;
    @XmlElement(name = "Relevance")
    protected short relevance;

    /**
     * Gets the value of the dataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DataUrlType }
     *     
     */
    public DataUrlType getDataUrl() {
        return dataUrl;
    }

    /**
     * Sets the value of the dataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataUrlType }
     *     
     */
    public void setDataUrl(DataUrlType value) {
        this.dataUrl = value;
    }

    /**
     * Gets the value of the navigableUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavigableUrl() {
        return navigableUrl;
    }

    /**
     * Sets the value of the navigableUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavigableUrl(String value) {
        this.navigableUrl = value;
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsin() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsin(String value) {
        this.asin = value;
    }

    /**
     * Gets the value of the relevance property.
     * 
     */
    public short getRelevance() {
        return relevance;
    }

    /**
     * Sets the value of the relevance property.
     * 
     */
    public void setRelevance(short value) {
        this.relevance = value;
    }

}
