//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlexaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlexaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContentData" type="{http://awis.amazonaws.com/doc/2005-07-11}ContentDataType"/>
 *         &lt;element name="Related" type="{http://awis.amazonaws.com/doc/2005-07-11}RelatedType"/>
 *         &lt;element name="TrafficData" type="{http://awis.amazonaws.com/doc/2005-07-11}TrafficDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlexaType", propOrder = {
    "contentData",
    "related",
    "trafficData"
})
public class AlexaType {

    @XmlElement(name = "ContentData", required = true)
    protected ContentDataType contentData;
    @XmlElement(name = "Related", required = true)
    protected RelatedType related;
    @XmlElement(name = "TrafficData", required = true)
    protected TrafficDataType trafficData;

    /**
     * Gets the value of the contentData property.
     * 
     * @return
     *     possible object is
     *     {@link ContentDataType }
     *     
     */
    public ContentDataType getContentData() {
        return contentData;
    }

    /**
     * Sets the value of the contentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentDataType }
     *     
     */
    public void setContentData(ContentDataType value) {
        this.contentData = value;
    }

    /**
     * Gets the value of the related property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedType }
     *     
     */
    public RelatedType getRelated() {
        return related;
    }

    /**
     * Sets the value of the related property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedType }
     *     
     */
    public void setRelated(RelatedType value) {
        this.related = value;
    }

    /**
     * Gets the value of the trafficData property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficDataType }
     *     
     */
    public TrafficDataType getTrafficData() {
        return trafficData;
    }

    /**
     * Sets the value of the trafficData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficDataType }
     *     
     */
    public void setTrafficData(TrafficDataType value) {
        this.trafficData = value;
    }

}
