//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dnocode.aws.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Response_QNAME = new QName("http://awis.amazonaws.com/doc/2005-07-11", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dnocode.aws.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseUrlInfoType }
     * 
     */
    public ResponseUrlInfoType createResponseType() {
        return new ResponseUrlInfoType();
    }

    /**
     * Create an instance of {@link RelatedLinkType }
     * 
     */
    public RelatedLinkType createRelatedLinkType() {
        return new RelatedLinkType();
    }

    /**
     * Create an instance of {@link AlexaType }
     * 
     */
    public AlexaType createAlexaType() {
        return new AlexaType();
    }

    /**
     * Create an instance of {@link SpeedType }
     * 
     */
    public SpeedType createSpeedType() {
        return new SpeedType();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link ResponseStatusType }
     * 
     */
    public ResponseStatusType createResponseStatusType() {
        return new ResponseStatusType();
    }

    /**
     * Create an instance of {@link OperationRequestType }
     * 
     */
    public OperationRequestType createOperationRequestType() {
        return new OperationRequestType();
    }

    /**
     * Create an instance of {@link UrlInfoResultType }
     * 
     */
    public UrlInfoResultType createUrlInfoResultType() {
        return new UrlInfoResultType();
    }

    /**
     * Create an instance of {@link OwnedDomainsType }
     * 
     */
    public OwnedDomainsType createOwnedDomainsType() {
        return new OwnedDomainsType();
    }

    /**
     * Create an instance of {@link ContentDataType }
     * 
     */
    public ContentDataType createContentDataType() {
        return new ContentDataType();
    }

    /**
     * Create an instance of {@link RelatedLinksType }
     * 
     */
    public RelatedLinksType createRelatedLinksType() {
        return new RelatedLinksType();
    }

    /**
     * Create an instance of {@link SiteDataType }
     * 
     */
    public SiteDataType createSiteDataType() {
        return new SiteDataType();
    }

    /**
     * Create an instance of {@link PerUserType }
     * 
     */
    public PerUserType createPerUserType() {
        return new PerUserType();
    }

    /**
     * Create an instance of {@link UsageStatisticType }
     * 
     */
    public UsageStatisticType createUsageStatisticType() {
        return new UsageStatisticType();
    }

    /**
     * Create an instance of {@link PageViewsType }
     * 
     */
    public PageViewsType createPageViewsType() {
        return new PageViewsType();
    }

    /**
     * Create an instance of {@link TrafficDataType }
     * 
     */
    public TrafficDataType createTrafficDataType() {
        return new TrafficDataType();
    }

    /**
     * Create an instance of {@link DataUrlType }
     * 
     */
    public DataUrlType createDataUrlType() {
        return new DataUrlType();
    }

    /**
     * Create an instance of {@link RelatedType }
     * 
     */
    public RelatedType createRelatedType() {
        return new RelatedType();
    }

    /**
     * Create an instance of {@link CategoryDataType }
     * 
     */
    public CategoryDataType createCategoryDataType() {
        return new CategoryDataType();
    }

    /**
     * Create an instance of {@link UsageStatisticsType }
     * 
     */
    public UsageStatisticsType createUsageStatisticsType() {
        return new UsageStatisticsType();
    }

    /**
     * Create an instance of {@link TimeRangeType }
     * 
     */
    public TimeRangeType createTimeRangeType() {
        return new TimeRangeType();
    }

    /**
     * Create an instance of {@link OwnedDomainType }
     * 
     */
    public OwnedDomainType createOwnedDomainType() {
        return new OwnedDomainType();
    }

    /**
     * Create an instance of {@link PerMillionType }
     * 
     */
    public PerMillionType createPerMillionType() {
        return new PerMillionType();
    }

    /**
     * Create an instance of {@link CategoriesType }
     * 
     */
    public CategoriesType createCategoriesType() {
        return new CategoriesType();
    }

    /**
     * Create an instance of {@link RankType }
     * 
     */
    public RankType createRankType() {
        return new RankType();
    }

    /**
     * Create an instance of {@link ReachType }
     * 
     */
    public ReachType createReachType() {
        return new ReachType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseUrlInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://awis.amazonaws.com/doc/2005-07-11", name = "Response")
    public JAXBElement<ResponseUrlInfoType> createResponse(ResponseUrlInfoType value) {
        return new JAXBElement<ResponseUrlInfoType>(_Response_QNAME, ResponseUrlInfoType.class, null, value);
    }

}
