//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseUrlInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseUrlInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OperationRequest" type="{http://awis.amazonaws.com/doc/2005-07-11}OperationRequestType"/>
 *         &lt;element name="UrlInfoResult" type="{http://awis.amazonaws.com/doc/2005-07-11}UrlInfoResultType"/>
 *         &lt;element name="ResponseStatus" type="{http://awis.amazonaws.com/doc/2005-07-11}ResponseStatusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseUrlInfoType", propOrder = {
    "operationRequest",
    "urlInfoResult",
    "responseStatus"
})
public class ResponseUrlInfoType {

    @XmlElement(name = "OperationRequest", required = true)
    protected OperationRequestType operationRequest;
    @XmlElement(name = "UrlInfoResult", required = true)
    protected UrlInfoResultType urlInfoResult;
    @XmlElement(name = "ResponseStatus", required = true)
    protected ResponseStatusType responseStatus;

    /**
     * Gets the value of the operationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OperationRequestType }
     *     
     */
    public OperationRequestType getOperationRequest() {
        return operationRequest;
    }

    /**
     * Sets the value of the operationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationRequestType }
     *     
     */
    public void setOperationRequest(OperationRequestType value) {
        this.operationRequest = value;
    }

    /**
     * Gets the value of the urlInfoResult property.
     * 
     * @return
     *     possible object is
     *     {@link UrlInfoResultType }
     *     
     */
    public UrlInfoResultType getUrlInfoResult() {
        return urlInfoResult;
    }

    /**
     * Sets the value of the urlInfoResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrlInfoResultType }
     *     
     */
    public void setUrlInfoResult(UrlInfoResultType value) {
        this.urlInfoResult = value;
    }

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatusType }
     *     
     */
    public ResponseStatusType getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatusType }
     *     
     */
    public void setResponseStatus(ResponseStatusType value) {
        this.responseStatus = value;
    }

}
