//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MedianLoadTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Percentile" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedType", propOrder = {
    "medianLoadTime",
    "percentile"
})
public class SpeedType {

    @XmlElement(name = "MedianLoadTime")
    protected short medianLoadTime;
    @XmlElement(name = "Percentile")
    protected byte percentile;

    /**
     * Gets the value of the medianLoadTime property.
     * 
     */
    public short getMedianLoadTime() {
        return medianLoadTime;
    }

    /**
     * Sets the value of the medianLoadTime property.
     * 
     */
    public void setMedianLoadTime(short value) {
        this.medianLoadTime = value;
    }

    /**
     * Gets the value of the percentile property.
     * 
     */
    public byte getPercentile() {
        return percentile;
    }

    /**
     * Sets the value of the percentile property.
     * 
     */
    public void setPercentile(byte value) {
        this.percentile = value;
    }

}
