//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrafficDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrafficDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataUrl" type="{http://awis.amazonaws.com/doc/2005-07-11}DataUrlType"/>
 *         &lt;element name="Asin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="UsageStatistics" type="{http://awis.amazonaws.com/doc/2005-07-11}UsageStatisticsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrafficDataType", propOrder = {
    "dataUrl",
    "asin",
    "rank",
    "usageStatistics"
})
public class TrafficDataType {

    @XmlElement(name = "DataUrl", required = true)
    protected DataUrlType dataUrl;
    @XmlElement(name = "Asin", required = true)
    protected String asin;
    @XmlElement(name = "Rank")
    protected byte rank;
    @XmlElement(name = "UsageStatistics", required = true)
    protected UsageStatisticsType usageStatistics;

    /**
     * Gets the value of the dataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link DataUrlType }
     *     
     */
    public DataUrlType getDataUrl() {
        return dataUrl;
    }

    /**
     * Sets the value of the dataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataUrlType }
     *     
     */
    public void setDataUrl(DataUrlType value) {
        this.dataUrl = value;
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsin() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsin(String value) {
        this.asin = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     */
    public byte getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     */
    public void setRank(byte value) {
        this.rank = value;
    }

    /**
     * Gets the value of the usageStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link UsageStatisticsType }
     *     
     */
    public UsageStatisticsType getUsageStatistics() {
        return usageStatistics;
    }

    /**
     * Sets the value of the usageStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageStatisticsType }
     *     
     */
    public void setUsageStatistics(UsageStatisticsType value) {
        this.usageStatistics = value;
    }

}
