//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.19 at 10:54:03 AM CEST 
//


package com.dnocode.aws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UsageStatisticType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsageStatisticType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TimeRange" type="{http://awis.amazonaws.com/doc/2005-07-11}TimeRangeType"/>
 *         &lt;element name="Rank" type="{http://awis.amazonaws.com/doc/2005-07-11}RankType"/>
 *         &lt;element name="Reach" type="{http://awis.amazonaws.com/doc/2005-07-11}ReachType"/>
 *         &lt;element name="PageViews" type="{http://awis.amazonaws.com/doc/2005-07-11}PageViewsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsageStatisticType", propOrder = {
    "timeRange",
    "rank",
    "reach",
    "pageViews"
})
public class UsageStatisticType {

    @XmlElement(name = "TimeRange", required = true)
    protected TimeRangeType timeRange;
    @XmlElement(name = "Rank", required = true)
    protected RankType rank;
    @XmlElement(name = "Reach", required = true)
    protected ReachType reach;
    @XmlElement(name = "PageViews", required = true)
    protected PageViewsType pageViews;

    /**
     * Gets the value of the timeRange property.
     * 
     * @return
     *     possible object is
     *     {@link TimeRangeType }
     *     
     */
    public TimeRangeType getTimeRange() {
        return timeRange;
    }

    /**
     * Sets the value of the timeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeRangeType }
     *     
     */
    public void setTimeRange(TimeRangeType value) {
        this.timeRange = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link RankType }
     *     
     */
    public RankType getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link RankType }
     *     
     */
    public void setRank(RankType value) {
        this.rank = value;
    }

    /**
     * Gets the value of the reach property.
     * 
     * @return
     *     possible object is
     *     {@link ReachType }
     *     
     */
    public ReachType getReach() {
        return reach;
    }

    /**
     * Sets the value of the reach property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReachType }
     *     
     */
    public void setReach(ReachType value) {
        this.reach = value;
    }

    /**
     * Gets the value of the pageViews property.
     * 
     * @return
     *     possible object is
     *     {@link PageViewsType }
     *     
     */
    public PageViewsType getPageViews() {
        return pageViews;
    }

    /**
     * Sets the value of the pageViews property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageViewsType }
     *     
     */
    public void setPageViews(PageViewsType value) {
        this.pageViews = value;
    }

}
